// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.18.3
// source: field_options.proto

package options

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldLogging_DisplayType int32

const (
	FieldLogging_Show       FieldLogging_DisplayType = 0
	FieldLogging_Hide       FieldLogging_DisplayType = 1
	FieldLogging_Obfuscate  FieldLogging_DisplayType = 2
	FieldLogging_TrimHead   FieldLogging_DisplayType = 3
	FieldLogging_TrimTail   FieldLogging_DisplayType = 4
	FieldLogging_TrimMiddle FieldLogging_DisplayType = 5
)

// Enum value maps for FieldLogging_DisplayType.
var (
	FieldLogging_DisplayType_name = map[int32]string{
		0: "Show",
		1: "Hide",
		2: "Obfuscate",
		3: "TrimHead",
		4: "TrimTail",
		5: "TrimMiddle",
	}
	FieldLogging_DisplayType_value = map[string]int32{
		"Show":       0,
		"Hide":       1,
		"Obfuscate":  2,
		"TrimHead":   3,
		"TrimTail":   4,
		"TrimMiddle": 5,
	}
)

func (x FieldLogging_DisplayType) Enum() *FieldLogging_DisplayType {
	p := new(FieldLogging_DisplayType)
	*p = x
	return p
}

func (x FieldLogging_DisplayType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldLogging_DisplayType) Descriptor() protoreflect.EnumDescriptor {
	return file_field_options_proto_enumTypes[0].Descriptor()
}

func (FieldLogging_DisplayType) Type() protoreflect.EnumType {
	return &file_field_options_proto_enumTypes[0]
}

func (x FieldLogging_DisplayType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldLogging_DisplayType.Descriptor instead.
func (FieldLogging_DisplayType) EnumDescriptor() ([]byte, []int) {
	return file_field_options_proto_rawDescGZIP(), []int{0, 0}
}

type FieldLogging struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Display     FieldLogging_DisplayType `protobuf:"varint,1,opt,name=display,proto3,enum=grpc.options.v1.FieldLogging_DisplayType" json:"display,omitempty"`
	Replacement string                   `protobuf:"bytes,2,opt,name=replacement,proto3" json:"replacement,omitempty"`
	HeadChars   int64                    `protobuf:"varint,3,opt,name=head_chars,json=headChars,proto3" json:"head_chars,omitempty"`
	TailChars   int64                    `protobuf:"varint,4,opt,name=tail_chars,json=tailChars,proto3" json:"tail_chars,omitempty"`
}

func (x *FieldLogging) Reset() {
	*x = FieldLogging{}
	if protoimpl.UnsafeEnabled {
		mi := &file_field_options_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldLogging) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldLogging) ProtoMessage() {}

func (x *FieldLogging) ProtoReflect() protoreflect.Message {
	mi := &file_field_options_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldLogging.ProtoReflect.Descriptor instead.
func (*FieldLogging) Descriptor() ([]byte, []int) {
	return file_field_options_proto_rawDescGZIP(), []int{0}
}

func (x *FieldLogging) GetDisplay() FieldLogging_DisplayType {
	if x != nil {
		return x.Display
	}
	return FieldLogging_Show
}

func (x *FieldLogging) GetReplacement() string {
	if x != nil {
		return x.Replacement
	}
	return ""
}

func (x *FieldLogging) GetHeadChars() int64 {
	if x != nil {
		return x.HeadChars
	}
	return 0
}

func (x *FieldLogging) GetTailChars() int64 {
	if x != nil {
		return x.TailChars
	}
	return 0
}

var file_field_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldLogging)(nil),
		Field:         55001,
		Name:          "grpc.options.v1.log_formatting",
		Tag:           "bytes,55001,opt,name=log_formatting",
		Filename:      "field_options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional grpc.options.v1.FieldLogging log_formatting = 55001;
	E_LogFormatting = &file_field_options_proto_extTypes[0]
)

var File_field_options_proto protoreflect.FileDescriptor

var file_field_options_proto_rawDesc = []byte{
	0x0a, 0x13, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x91, 0x02, 0x0a, 0x0c, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x4c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x12, 0x43, 0x0a, 0x07, 0x64, 0x69, 0x73,
	0x70, 0x6c, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x4c, 0x6f, 0x67, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61,
	0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x12, 0x20,
	0x0a, 0x0b, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x65, 0x61, 0x64, 0x5f, 0x63, 0x68, 0x61, 0x72, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x68, 0x65, 0x61, 0x64, 0x43, 0x68, 0x61, 0x72, 0x73, 0x12,
	0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x69, 0x6c, 0x5f, 0x63, 0x68, 0x61, 0x72, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x61, 0x69, 0x6c, 0x43, 0x68, 0x61, 0x72, 0x73, 0x22, 0x5c,
	0x0a, 0x0b, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a,
	0x04, 0x53, 0x68, 0x6f, 0x77, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x69, 0x64, 0x65, 0x10,
	0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4f, 0x62, 0x66, 0x75, 0x73, 0x63, 0x61, 0x74, 0x65, 0x10, 0x02,
	0x12, 0x0c, 0x0a, 0x08, 0x54, 0x72, 0x69, 0x6d, 0x48, 0x65, 0x61, 0x64, 0x10, 0x03, 0x12, 0x0c,
	0x0a, 0x08, 0x54, 0x72, 0x69, 0x6d, 0x54, 0x61, 0x69, 0x6c, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a,
	0x54, 0x72, 0x69, 0x6d, 0x4d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x10, 0x05, 0x3a, 0x65, 0x0a, 0x0e,
	0x6c, 0x6f, 0x67, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x1d,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd9, 0xad,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4c, 0x6f, 0x67,
	0x67, 0x69, 0x6e, 0x67, 0x52, 0x0d, 0x6c, 0x6f, 0x67, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x30, 0x78, 0x65, 0x66, 0x35, 0x33, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x3b, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_field_options_proto_rawDescOnce sync.Once
	file_field_options_proto_rawDescData = file_field_options_proto_rawDesc
)

func file_field_options_proto_rawDescGZIP() []byte {
	file_field_options_proto_rawDescOnce.Do(func() {
		file_field_options_proto_rawDescData = protoimpl.X.CompressGZIP(file_field_options_proto_rawDescData)
	})
	return file_field_options_proto_rawDescData
}

var file_field_options_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_field_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_field_options_proto_goTypes = []interface{}{
	(FieldLogging_DisplayType)(0),     // 0: grpc.options.v1.FieldLogging.DisplayType
	(*FieldLogging)(nil),              // 1: grpc.options.v1.FieldLogging
	(*descriptorpb.FieldOptions)(nil), // 2: google.protobuf.FieldOptions
}
var file_field_options_proto_depIdxs = []int32{
	0, // 0: grpc.options.v1.FieldLogging.display:type_name -> grpc.options.v1.FieldLogging.DisplayType
	2, // 1: grpc.options.v1.log_formatting:extendee -> google.protobuf.FieldOptions
	1, // 2: grpc.options.v1.log_formatting:type_name -> grpc.options.v1.FieldLogging
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_field_options_proto_init() }
func file_field_options_proto_init() {
	if File_field_options_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_field_options_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldLogging); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_field_options_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_field_options_proto_goTypes,
		DependencyIndexes: file_field_options_proto_depIdxs,
		EnumInfos:         file_field_options_proto_enumTypes,
		MessageInfos:      file_field_options_proto_msgTypes,
		ExtensionInfos:    file_field_options_proto_extTypes,
	}.Build()
	File_field_options_proto = out.File
	file_field_options_proto_rawDesc = nil
	file_field_options_proto_goTypes = nil
	file_field_options_proto_depIdxs = nil
}
